runners:
  - name: "x86-aws-runner"
    cloud: "aws"
    instance_type: "c6i.large"
    # Ubuntu-20.4, ami image
    machine_image: "ami-06fd8a495a537da8b"
    preemptible: false
    labels:
      - "cirun-aws-runner"
      
  - name: "arm-aws-runner"
    cloud: "aws"
    instance_type: "c7g.large"
    # AMI for ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server
    machine_image: "ami-0229f8cfc24033d05"
    preemptible: false
    labels:
      - "cirun-arm-runner"