from easyfs import File

HEADER = """#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

source ./dependencies.sh

source ./install_command.sh

"""


class InstallSH(File):
    def __init__(self) -> None:
        super().__init__(HEADER.encode())
