from easyfs import File

HEADER = """#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

{command}
"""


class InstallCommandSH(File):
    def __init__(self, command: str) -> None:
        super().__init__(HEADER.format(command=command).encode())
