from typing import List, Optional

import pytest
from helpers import execute_current_python_in_container


# @pytest.mark.skip(reason="not implemented yet")
@pytest.mark.parametrize(
    "test_command,excpected_result,image,repo,target,flags,docker_platform",
    [
        (
            "upx --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "upx/upx",
            "upx",
            "",
            "linux/amd64",
        ),
        (
            "doctl version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "digitalocean/doctl",
            "doctl",
            "",
            "linux/amd64",
        ),
        (  # classic
            "argocd --help",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "argoproj/argo-cd",
            "argocd",
            "",
            "linux/amd64",
        ),
        (  # alpine
            "argocd --help",
            0,
            "mcr.microsoft.com/devcontainers/base:alpine",
            "argoproj/argo-cd",
            "argocd",
            "",
            "linux/amd64",
        ),
        (  # arm
            "argocd --help",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "argoproj/argo-cd",
            "argocd",
            "",
            "linux/arm64",
        ),
        (  # two binaries at same repo
            "which kubectx",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "ahmetb/kubectx",
            "kubectx",
            "",
            "linux/amd64",
        ),
        (  # two binaries at same repo
            "which kubens",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "ahmetb/kubectx",
            "kubens",
            "",
            "linux/amd64",
        ),
        (  # control group for arm
            "terrascan version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "tenable/terrascan",
            "terrascan",
            "",
            "linux/amd64",
        ),
        (  # arm
            "terrascan version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "tenable/terrascan",
            "terrascan",
            "",
            "linux/arm64",
        ),
        (
            "gh --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "cli/cli",
            "gh",
            "",
            "linux/amd64",
        ),
        (  # folder named btop in archive
            "btop --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "aristocratos/btop",
            "btop",
            "",
            "linux/amd64",
        ),
        (  # zip archive for linux
            "exa --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "ogham/exa",
            "exa",
            "",
            "linux/amd64",
        ),
        (  # .apk file
            "duf --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "muesli/duf",
            "duf",
            "",
            "linux/amd64",
        ),
        (  # .pem file
            "caddy version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "caddyserver/caddy",
            "caddy",
            "",
            "linux/amd64",
        ),
        (  # has positive "static"
            "cas --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "codenotary/cas",
            "cas",
            "",
            "linux/amd64",
        ),
        (  # release regex
            "bw --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "bitwarden/clients",
            "bw",
            "--release-tag-regex 'cli\\-'",
            "linux/amd64",
        ),
        (  # date based version
            "youtubeuploader -version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "porjo/youtubeuploader",
            "youtubeuploader",
            "",
            "linux/amd64",
        ),
        (  # gz (not tar)
            "chisel --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "jpillora/chisel",
            "chisel",
            "",
            "linux/amd64",
        ),
        (  # has negative "musl"
            "cyclonedx --version",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "CycloneDX/cyclonedx-cli",
            "cyclonedx",
            "",
            "linux/amd64",
        ),
        (
            "pwsh --version",
            1,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "PowerShell/PowerShell",
            "pwsh",
            "",
            "linux/amd64",
        ),
        (
            "type extractor",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "Azure/apiops",
            "extractor",
            "--asset-regex '^extractor\.linux-.+\.exe$' --no-filter-assets-by-platform",
            "linux/amd64",
        ),
        (
            "type extractor",
            0,
            "mcr.microsoft.com/vscode/devcontainers/python:3.10-bullseye",
            "Azure/apiops",
            "extractor",
            "--asset-regex '^extractor\.linux-.+\.exe$' --no-filter-assets-by-platform",
            "linux/arm64",
        ),
    ],
)
def test_gh_release_install(
    test_command,
    excpected_result: int,
    image: str,
    repo: List[str],
    target: str,
    flags: str,
    docker_platform: str,
) -> None:
    full_test_command = f"sudo PYTHONPATH=$PYTHONPATH python3 -m nanolayer install gh-release {repo} {target} {flags} && {test_command}"

    assert excpected_result == execute_current_python_in_container(
        test_command=full_test_command,
        image=image,
        docker_platform=docker_platform,
        nanolayer_version="v0.4.45",
    )
