from typing import Optional, Dict, Union
from devcontainer_contrib.models.devcontainer_feature import FeatureOption
from devcontainer_contrib.models.devcontainer_feature_definition import (
    FeatureDependencies,
    FeatureDependency,
)

FEATMAKE_LINK = (
    "https://github.com/devcontainers-contrib/cli/releases/download/v0.0.8/featmake"
)

HEADER = """#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

ensure_curl () {{
    if ! type curl >/dev/null 2>&1; then
        apt-get update -y && apt-get -y install --no-install-recommends curl
    fi 
}}

ensure_curl

curl -sSL {featmake_link} -o featmake

{dependency_installation_lines}
"""


class DependenciesSH:
    REF_PREFIX = "$options."

    def __init__(
        self,
        dependencies: Optional[FeatureDependencies],
        options: Optional[Dict[str, FeatureOption]],
    ) -> None:
        self.dependencies = dependencies
        self.options = options

    @staticmethod
    def is_param_ref(param_value: str) -> bool:
        return param_value.startswith(DependenciesSH.REF_PREFIX)

    def create_install_command(
        self, feature_oci: str, params: Dict[str, Union[str, bool]]
    ):
        envs = {}
        for param_name, param_value in params.items():
            if isinstance(param_value, str):
                envs[param_name.upper()] = param_value
            else:
                envs[param_name.upper()] = str(param_value).lower()

        stringified_envs = " ".join([f'{env}="{val}"' for env, val in envs.items()])

        comment = "# installing {feature_oci}\n"
        return f'{comment}{stringified_envs} ./featmake "{feature_oci}"'

    @staticmethod
    def resolve_param_ref(
        param_ref: str, options: Optional[Dict[str, FeatureOption]]
    ) -> str:
        if options is None:
            raise ValueError(
                f"option reference was given: '{param_ref}' but no options exists"
            )

        option_name = param_ref.replace(DependenciesSH.REF_PREFIX, "")

        option = options.get(option_name, None)
        if option is None:
            raise ValueError(
                f"could not resolve option reference: '{param_ref}' please ensure you spelled the option name right ({option})"
            )
        return f"${option_name}".upper()

    def to_str(self) -> str:
        if self.dependencies is None or len(self.dependencies) == 0:
            return ""

        installation_lines = []
        for feature_dependency in self.dependencies:
            feature_dependency: FeatureDependency
            resolved_params = {}
            for param_name, param_value in feature_dependency.options.items():
                if isinstance(param_value, str):
                    if DependenciesSH.is_param_ref(param_value):
                        param_value = DependenciesSH.resolve_param_ref(
                            param_value, self.options
                        )

                resolved_params[param_name] = param_value
            installation_lines.append(
                self.create_install_command(feature_dependency.feature, resolved_params)
            )

        return HEADER.format(
            dependency_installation_lines="\n\n".join(installation_lines),
            featmake_link=FEATMAKE_LINK,
        )
