HEADER = """#!/usr/bin/env bash
# This code was generated by the devconainer-contrib cli 
# For more information: https://github.com/devcontainers-contrib/cli 

set -e

source dev-container-features-test-lib

check "{command}" {command}

reportResults
"""


class TestSH:
    def __init__(self, command: str) -> None:
        self.command = command

    def to_str(self) -> str:
        return HEADER.format(command=self.command)
