name: Release Binaries For Arch

on:
  workflow_dispatch:
    inputs:
      triple_target:
        description: 'rust cargo triple target for pyoxidizer'
        required: true
        type: choice
        options:
        - "x86_64-unknown-linux-gnu"
        - "aarch64-unknown-linux-gnu"

      binary_name:
        description: 'output binary name'
        required: false
        type: string
        default: "dcontainer"

      runner:
        description: 'runner name'
        required: false
        type: string
        default: "ubuntu-latest"


  workflow_call:
    inputs:
      triple_target:
        description: 'rust cargo triple target for pyoxidizer'
        required: true
        type: string
  
  
      binary_name:
        description: 'output binary name'
        required: false
        type: string
        default: "dcontainer"
        
  
      runner:
        description: 'runner name'
        required: false
        type: string
        default: "ubuntu-latest"
        
permissions:
  contents: write
  discussions: write


jobs:
  release-publish:
    env:
      binary_name: dcontainer
    runs-on: ${{ inputs.runner }}  # assume python3 exists

    steps:
      - uses: actions/checkout@v3

      - name: Build Python Package
        run: |
          apt-get install -y python3-pip python3-venv
          python3 -m pip install --upgrade pip 
          python3 -m pip install --upgrade build setuptools wheel  setuptools-scm
          python3 -m build --wheel
  
      - name: Build Binary using Pyoxidizer
        id: run_pyoxidizer
  
        run: |
          apt-get install -y build-essential
          python3 -m pip install --upgrade pip 
          python3 -m pip install pyoxidizer
  
          oxidizer_location=$GITHUB_WORKSPACE
          wheel_location=./dist/$(ls dist | grep .whl)
          target_triple=${{ inputs.triple_target }}
          binary_name=${{ inputs.binary_name }} 
          run_command="from dcontainer.__main__ import main; main()"
          python_version="3.10"
  
          pyoxidizer build exe \
            --path $oxidizer_location \
            --release \
            --var wheel_location $wheel_location \
            --var run_command "$run_command" \
            --var python_version $python_version \
            --var app_name $binary_name \
            --target-triple $target_triple 
  
          pyoxidizer analyze "$oxidizer_location/build/$target_triple/release/exe/$binary_name"
          
          strip $oxidizer_location/build/$target_triple/release/exe/$binary_name
          
          tar -zcvf $GITHUB_WORKSPACE/build/$binary_name-$target_triple.tgz "$oxidizer_location/build/$target_triple/release/exe/$binary_name"
  
          echo "binary_location=$GITHUB_WORKSPACE/build/$binary_name-$target_triple.tgz" >> "$GITHUB_OUTPUT"
  
      - name: Create GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
            files: |
              ${{ steps.run_pyoxidizer.outputs.binary_location }}
  