name: Release Binaries On EC2 - All
on: 
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  discussions: write
       

jobs:
 
  release-publish-x86_64:
    uses: ./.github/workflows/release-binaries-on-ec2.yaml
    secrets: inherit
    with:
      triple_target: "x86_64-unknown-linux-gnu"
      binary_name: "dcontainer"
      instance_type: "c6i.large"
      # ami_id: ami-0b0ea68c435eb488d # ubuntu 16.04
      ami_id: ami-05bdb9a595eeef95a # ubuntu 18.04
      # ami_id: ami-07a72d328538fc075 # ubuntu 20.04 
      # ami_id: ami-007855ac798b5175e # ubuntu 22.04
      
 
  release-publish-arm64:
    uses: ./.github/workflows/release-binaries-on-ec2.yaml
    secrets: inherit
    with:
      triple_target: "aarch64-unknown-linux-gnu"
      binary_name: "dcontainer"
      instance_type: "c7g.large"
      # ami_id: ami-04b3c39a8a1c62b76 # ubuntu 16.04
      ami_id: ami-0ccbd1a24ded2a2a8 # ubuntu 18.04
      # ami_id: ami-094bbbc35cbcb6a1a # ubuntu 20.04
      # ami_id: ami-0c6c29c5125214c77 # ubuntu 22.04