name: Release Binaries On EC2 - All
on: 
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  discussions: write
       

jobs:
 
  release-publish-x86_64:
    uses: ./.github/workflows/release-binaries-on-ec2.yaml
    with:
      triple_target: "x86_64-unknown-linux-gnu"
      binary_name: "dcontainer"
      instance_type: "c6i.large"
      ami_id: ami-0263e4deb427da90e # ubuntu 18.04
      # ami_id: ami-09cd747c78a9add63 # ubuntu 20.04 
      # ami_id: ami-0557a15b87f6559cf # ubuntu 22.04
      
 
  release-publish-arm64:
    uses: ./.github/workflows/release-binaries-on-ec2.yaml
    with:
      triple_target: "aarch64-unknown-linux-gnu"
      binary_name: "dcontainer"
      instance_type: "c7g.large"
      ami_id: ami-0e5599794d252b611 # ubuntu 18.04
      # ami_id: ami-054cb116359624aa3 # ubuntu 20.04
      # ami_id: ami-0f9bd9098aca2d42b # ubuntu 22.04