name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    # # Required permissions
    # permissions:
    #   pull-requests: read
    # # Set job outputs to values from filter step
    outputs:
      relevant_files: ${{ steps.filter.outputs.relevant_files }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          relevant_files:
            - 'dcontainer/**'
            - 'tests/**'

  run-tests:
    needs: [changes]  
    if: ${{ (needs.changes.outputs.relevant_files == 'true') || (github.event_name	== 'workflow_dispatch') }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            runner: "ubuntu-latest"
          }
          - {
            runner: "macos-12"
          }
          - {
            runner: "x86-aws-runner--1-${{ github.run_id }}"
          }
          - {
            runner: "arm-aws-runner--1-${{ github.run_id }}"
          }

    runs-on: ${{ matrix.config.runner }}
    
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli


      - name: "Set up Python 3.8"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: "Install python dependencies"
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade build setuptools wheel  setuptools-scm
          pip install -r requirements.txt -r requirements-generate.txt -r requirements-dev.txt
      - name: "Test with pytest"
        run: |
          python -m pytest -s -v --ignore=tests/devcontainer/feature_generation